PREFIX ex: <http://specimenkb.sdei.senckenberg.de/ontology#>

SELECT ?publication ?title (COUNT(DISTINCT ?specimen) AS ?specimenCount)
WHERE {
  ?publication ex:mentionsTypeSpecimen ?specimen .

  OPTIONAL { ?publication dcterms:title ?title . }
}
GROUP BY ?publication ?title
ORDER BY DESC(?specimenCount)
