PREFIX ex: <http://specimenkb.sdei.senckenberg.de/ontology#>

SELECT ?year (COUNT(DISTINCT ?specimen) AS ?specimenCount)
WHERE {
  ?publication ex:mentionsTypeSpecimen ?specimen ;
               dcterms:issued ?date .

  BIND(YEAR(?date) AS ?year)
}
GROUP BY ?year
ORDER BY ?year
