PREFIX ex: <http://specimenkb.sdei.senckenberg.de/ontology#>
PREFIX dwc: <http://rs.tdwg.org/dwc/terms/>

SELECT ?synonym ?acceptedName
WHERE {
    ?synonym ex:subjectiveJuniorSynonymOf ?acceptedTaxon .
    ?acceptedTaxon dwc:scientificName ?acceptedName .

    FILTER(?acceptedTaxon = <TARGET_TAXON_URI>)
}
